kind: Deployment
apiVersion: apps/v1
metadata:
    name: hostname-101-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: hostname
            version: v101
    template:
        metadata:
            labels:
                app: hostname
                version: v101
        spec:
            containers:
             - name: nginx-hostname
               image: kubegoldenguide/nginx-hostname:1.0.1
               ports:
                - containerPort: 80
