kind: Deployment
apiVersion: apps/v1
metadata:
    name: hostname-102-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hostname
            version: v102
    template:
        metadata:
            labels:
                app: hostname
                version: v102
        spec:
            containers:
             - name: nginx-hostname
               image: kubegoldenguide/nginx-hostname:1.0.2
               ports:
                - containerPort: 80
