kind: Pod
apiVersion: v1
metadata:
    name: liveliness-readiness-pod
spec:
    containers:
        - name: liveliness-readiness-pod
          image: python:2.7-alpine

          readinessProbe:
              initialDelaySeconds: 5
              failureThreshold: 1
              httpGet:
                  path: /
                  port: 8000
          env:
              - name: DELAY_START
                value: "45"
          command: ["/bin/sh"]
          args: ["-c",
                "echo 'Sleeping...';
                sleep $(DELAY_START);
                echo 'Starting server...';
                python -m SimpleHTTPServer"]

