kind: Pod
apiVersion: v1
metadata:
    name: liveliness-readiness-pod
spec:
    containers:
        - name: server
          image: python:2.7-alpine

          readinessProbe:
              initialDelaySeconds: 30
              failureThreshold: 4
              httpGet:
                  path: /
                  port: 8000
          
          livenessProbe:
              initialDelaySeconds: 60
              periodSeconds: 5
              exec:
                command: ["ls", "index.html"]

          env:
              - name: DELAY_START
                value: "45"
          command: ["/bin/sh"]
          args: ["-c",
                "echo 'Sleeping...';
                sleep $(DELAY_START);
                echo 'Starting server...';
                python -m SimpleHTTPServer"]

