kind: Pod
apiVersion: v1
metadata:
    name: pod-two
    namespace: red-team
spec:
    containers:
      - name: nginx-pod-two
        image: nginx
        resources:
            requests:
                memory: 512m
                cpu: "0.5"
            limits:
                memory: 1024m
                cpu: "1"
