kind: Pod
apiVersion: v1
metadata:
    name: pod-using-secret
spec:
    volumes:
      - name: api-secret-volume
        secret:
            secretName: api-authentication-secret
    containers:
      - name: container-secret
        image: nginx
        volumeMounts:
          - name: api-secret-volume
            mountPath: /etc/secret
