kind: ResourceQuota
apiVersion: v1
metadata:
    name: red-team-resource-quota
    namespace: red-team
spec:
    hard:
        pods: 5

        "requests.cpu": "2"
        "requests.memory": 1024m

        "limits.cpu": "4"
        "limits.memory": 2048m
